### ISSUE TITLE
##  Upload Files event handler

### ISSUE THREAD

**Issue by Xlient** [Xlient/EasySub#1]
The main idea here is to  get the users' uploaded file in when it changes via Onchange

Create a method that will create a new file with a  random name we give it and its file extension 

save it to a folder maybe `Devlopement\unsafe_upload` like the docs linked below

 and return the path as a string  for another method

[Useful documentation i found for this](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=server#upload-files-with-progress)

**Comment by wmambo** [comment]
The document isn't opening up

**Comment by Xlient** [comment]
@WanjiruMambo  Sorry should be fixed now

**Comment by wmambo** [comment]
Yeah, I saw you shared it on discord. Looking over it right now

**Comment by wmambo** [comment]
`private async Task LoadFiles(InputFileChange e)
    {
          var trustedFileName = Path.GetRandomFileName();
          var path = Path.Combine(Environment.ContentRootPath,
          Environment.EnvironmentName, "unsafe_uploads", trustedFileName);

          return path;
    }
`

**Comment by wmambo** [comment]
was that what you meant?

Also, what did you say you wanted us to change the name environment to?

**Comment by Xlient** [comment]
This looks good! I meant `Environment.EnvironmentName` will get the current environment name . Which is set to Development now  so the path would look like Development\unsafe_uploads\<something file name>.

**Comment by Xlient** [comment]
also we need to copy the file the user uploaded to the folder we made 👍🏾

**Comment by wmambo** [comment]
okay

**Comment by wmambo** [comment]
``` public static async Task CopyFileAsync(string sourceFile, string destinationFile)
{
    using (var sourceStream = new FileStream(sourceFile, FileMode.Open, FileAccess.Read, FileShare.Read, 4096, FileOptions.Asynchronous | FileOptions.SequentialScan))
    using (var destinationStream = new FileStream(destinationFile, FileMode.CreateNew, FileAccess.Write, FileShare.None, 4096, FileOptions.Asynchronous | FileOptions.SequentialScan))
        await sourceStream.CopyToAsync(destinationStream);
}

```

**Comment by wmambo** [comment]
we can player around with the buffer size, the 4096

**Comment by Xlient** [comment]
yeah definitely, this looks sweet! cant wait to test it when we get our UI up

**Comment by wmambo** [comment]
Wow. I'm so happy to hear that I was able to implement what you had tasked me to do

I was worried that I would not have been able to do it

Thank you so much for guiding me on how to do it

**Comment by Xlient** [comment]
No problem! you got this  Wanjiru!!!

**Comment by wmambo** [comment]
@CKanja 

<Upload Action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
        Name="files"
        Drag
        Multiple
        OnSingleCompleted="OnSingleCompleted">        
    <p class="ant-upload-drag-icon">
        <Icon Type="inbox" />
    </p>
    <p class="ant-upload-text">Click or drag file to this area to upload</p>
    <p class="ant-upload-hint">
        Support for a single or bulk upload. Strictly prohibit from uploading company data or other
        band files
    </p>
</Upload>

@code {

    void OnSingleCompleted(UploadInfo fileinfo)
    {
        if (fileinfo.File.State == UploadState.Success)
        {
            var result = fileinfo.File.GetResponse<ResponseModel>();
            fileinfo.File.Url = result.url;
        }
    }

    public class ResponseModel
    {
        public string name { get; set; }

        public string status { get; set; }

        public string url { get; set; }

        public string thumbUrl { get; set; }
    }
}

**Comment by wmambo** [comment]
And then we can call the method

**Comment by CKanja** [comment]
yaaay Wanjiru!
Thank you! Let me finish up on the page, and share
Looking forward to y'alls feedback

**Comment by CKanja** [comment]
I've just added the files to the repo (index.html, index.css, styles.css, images folder), kindly let me know if they are working fine on your end.

Let me know what I could add/remove, also looking forward to seeing all the moving parts coming together :)

**Comment by CKanja** [comment]
We can def improve on the wording 😅

**Comment by CKanja** [comment]
of the content on the page
